on:
  push:
    branches: [main, master]
  pull_request:
jobs:
    Unit-Tests:
        runs-on: ubuntu-latest

        steps:
            - name: Print job info
              run: |
                echo "This job was automatically triggered by a ${{ github.event_name }} event. It is now running on a ${{ runner.os }} server hosted by GitHub! The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
                echo Running python version `python -V`

            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3

            - name: Install this package
              run: |
                  pip install --upgrade pip
                  pip install --no-cache-dir ".[dev,alkaid]"

            - name: Run the unit tests
              run: pytest -rs
